routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\InventoryController;
use App\Http\Controllers\Admin\OrderController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


//=======authentication=======
Route::get('/dashboard',[HomeController::class, 'dash'])->middleware(['auth', 'verified','CheckAdmin'])->name('admin.dashboard');

Route::get('/redirect',[HomeController::class,'redirect']);

//Route::get('/redirect/',[HomeController::class,'redirect']);

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';






//Route::get('/home', [App\Http\Controllers\Controller::class,'dashboard'])->name('dashboard');
Route::middleware(['CheckAdmin'])->group(function () {
    Route::name('admin.')->group(function () {


        Route::get('/inventory', function () {
            return view('admin.pages.inventory.inventory');
        })->name('inventory');


//createproduct==========================


        Route::get('/product', [ProductController::class, 'index'])->name('product');


        Route::get('/createproduct', [ProductController::class, 'create'])->name('createproduct');
        Route::post('/storeproduct', [ProductController::class, 'store'])->name('storeproduct');
//Route::get('/show1',[ProductController::class, 'index1'])->name('show1');
        Route::get('/related/{id}', [ProductController::class, 'related'])->name('makerelated');
        Route::post('/storerelated', [ProductController::class, 'storeRelated'])->name('storerelated');
        Route::get('show', [ProductController::class, 'show'])->name('showproductdetails');
        Route::get('/editproduct/{id}', [ProductController::class, 'edit'])->name('editproduct');
        Route::post('/updateproduct/{id}', [ProductController::class, 'update'])->name('updateproduct');
        Route::get('/deleteproduct/{id}', [ProductController::class, 'destroy'])->name('deleteproduct');
        Route::get('/showdetailsproduct/{id}', [ProductController::class, 'show'])->name('showdetailsproduct');


        //====================category==========
        Route::get('/createcategory', [CategoryController::class, 'create'])->name('createcategory');
        Route::post('/storecategory', [CategoryController::class, 'store'])->name('storecategory');
        Route::get('/category', [CategoryController::class, 'index'])->name('category');
        Route::get('/showproduct/{category_id}', [CategoryController::class, 'showProduct'])->name('showproduct');
        Route::get('/deleteproductcat/{id}', [CategoryController::class, 'delete'])->name('deleteproductcat');

        Route::get('/editcategory/{id}', [CategoryController::class, 'edit'])->name('editcategory');
        Route::post('/updatecategory/{id}', [CategoryController::class, 'update'])->name('updatecategory');
        Route::get('/deletecategory/{id}', [CategoryController::class, 'destroy'])->name('deletecategory');
        Route::get('/deleterelation/{id}', [CategoryController::class, 'destroyRelation'])->name('deleterelation');
        Route::get('/relatedcat/{id}', [CategoryController::class, 'relatedCat'])->name('makerelatedcat');
        Route::post('/storerelatedcat', [CategoryController::class, 'storeRelated'])->name('storerelatedcat');
        //===========================User====================
        Route::get('/createuser', [UserController::class, 'create'])->name('createuser');
        Route::post('/storeuser', [UserController::class, 'store'])->name('storeuser');
        Route::get('/user', [UserController::class, 'index'])->name('user');

        Route::get('/edituser/{id}', [UserController::class, 'edit'])->name('edituser');
        Route::post('/updateuser/{id}', [UserController::class, 'update'])->name('updateuser');
        Route::get('/deleteuser/{id}', [UserController::class, 'destroy'])->name('deleteuser');
        Route::get('/showuser/{id}', [UserController::class, 'show'])->name('showuser');

//================================Inventory=========================


        Route::get('/creatinv', [InventoryController::class, 'create'])->name('createinv');
        Route::post('/storeinv', [InventoryController::class, 'store'])->name('storeinv');
        Route::get('/inventory', [InventoryController::class, 'index'])->name('inventory');

        Route::get('/editinv/{id}', [InventoryController::class, 'edit'])->name('editinv');
        Route::post('/updateinv/{id}', [InventoryController::class, 'update'])->name('updateinv');


//=================Orders========
        Route::get('/orders', [OrderController::class, 'index'])->name('orders');
        Route::get('/delivered/{created_at}', [OrderController::class, 'delivered'])->name('delivered');
//        Route::get('/deliveredone/{id}', [OrderController::class, 'deliveredOne'])->name('deliveredone');
        Route::get('/showorderdetails/{id}', [OrderController::class, 'showOrderdetails'])->name('showorderdetails');
        Route::get('/showallorders/{name}', [OrderController::class, 'showAllOrders'])->name('showallorders');
    });
});

routes/web.php
<?php

use App\Http\Controllers\Front\CartController;
use App\Http\Controllers\Front\OrderController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index']);



Route::get('/redirect',[HomeController::class,'redirect']);
Route::get('/home', [HomeController::class, 'home'])->name('home');
Route::get('/show/{id}', [HomeController::class, 'show'])->name('showpro');


//=========================Cart====

Route::get('/deletcat/{id}', [CartController::class, 'destroy'])->name('deletcat');
Route::get('/showprowebdetails/{id}',[CartController::class, 'showProWebDetails'])->name('showprowebdetails');
Route::post('/addtocart/{id}',[CartController::class, 'addToCart'])->name('addtocart');
Route::get('/cart', [CartController::class, 'showCart'])->name('cart');


Route::get('/cashorder', [OrderController::class, 'cashOrder'])->name('cashorder');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Category extends Model
{
    use HasFactory;


    protected $guarded = [];

    protected $fillable = [
        'name'
    ];

    public function products (): BelongsToMany
    {
        return $this->belongsToMany(Product::class, 'category_product');
    }


}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use App\Models\Inventory;
use Illuminate\Http\Request;

class CategoryController extends Controller
{




    public function index()
    {    $categories = Category::get();

         Return view('admin.pages.category.category', compact('categories'));


    }


    public function create()
    {

    Return view('admin.pages.category.createcategory');
    }


    public function store(Request $request)
    {

        $request->validate([
            'name' => ['required', 'string', 'max:255'],

        ]);
        $input = $request->all();


        Category::create($input);
        return redirect('/admin/category')->with(['success' => 'تم إضافة الفئة بنجاح']);
    }


    public function show(string $id)
    {
        $categories = Category::find($id);

        Return view('admin.pages.category.relatedproduct', compact('categories'));
    }


    public function edit(string $id)
    {
        return view('admin.pages.category.editcategory')
        ->with('category',Category::where('id',$id)->first());
    }

    public function update(Request $request, string $id)
    {

        $request->validate([
            'name' => ['required', 'string', 'max:255'],

        ]);
        Category::where('id',$id)
        ->update([ 'name' => $request->input('name')]);

        return redirect('/admin/category')->with(['success' => 'تم تعديل الفئة بنجاح']);
    }


    public function destroy(string $id)
    {
        Category::where('id', $id)->delete();
        return redirect('/admin/category')
        ->with('deletemessage', 'تم حذف الفئة بنجاح');
    }


    public function showProduct($category_id){

        $categories = Category::find($category_id);

        return view('admin.pages.category.relatedproduct', compact('categories'));



    }


        public function  delete($id)
        {
            Product::where('id', $id)->delete();
            $categories = Category::get();
            return view('admin.pages.category.relatedproduct', compact('categories'))
            ->with('deletemessage', 'تم حذف المنتج بنجاح');

    }


    public function destroyRelation(Request $request){

$id=$request->id;
$category_id=$request->category_id;

$categories = Category::find($request ->category_id);


$categories -> products () -> detach ($id); //بتعمل update  للعلاقة في جدول ال pivot       اي اذا بدي اعمل تعديل على العلاقة بين منتج و كاتيجوري



return redirect(route('admin.showproduct', $category_id))->with(['success' => 'تم حذف العلاقة بنجاح']);




    }



    public function relatedCat($id){

        $products = Product::select('id', 'name') -> get();
        $allcategories =  Category::where('id', $id)->get();

        return view ('admin.pages.category.category-with-product', compact('products', 'allcategories'));
    }

    public function storeRelated(Request $request){


        $category_id=$request ->category_id;
        $category = Category::find($request ->category_id);
         if(!$category)
         return abort ('404');

         $category -> products () -> syncWithoutDetaching ($request->product_id);  // رح تعمل اضافة لعلاقات جديدة مع الحفاظ على القديم بدون تكرار


return redirect(route('admin.showproduct', $category_id))->with(['successp' => 'تم ربط المنتجات بنجاح']);


}


}


// return Category::with('products')->find(1);

//سوف تستخدم لاحقا
        //return view('admin. pages.category.showrelatedproduct',compact('products'));



         // return view('admin.pages.category.relatedproduct')
        // ->with('deletecatmessage', 'تم حذف العلاقة بنجاح');


         //$product -> categories () -> attach ($request->category_id);       تسمح  بتكرار العلاقة في ال pivot table
         //$product -> categories () -> sync ($request->category_id);  بتعمل update  للعلاقة في جدول ال pivot       اي اذا بدي اعمل تعديل على العلاقة بين منتج و كاتيجوري

resources/views/admin/pages/category/category-with-product.blade.php
@extends('admin.layout.app')
@section('content')







<div class="container">

    <div class="row x">

        <div class=" col-12">
            <br>
            <br>
            <br>
            <form  action="{{ route('admin.storerelatedcat') }}" method="POST" enctype="multipart/form-data">
                @csrf


                <div class="form-group">
                    <label for="formGroupExampleInput">chose the name of product</label>

                    <select name="product_id[]" class=" form-control   selectpicker" multiple="multiple" data-live-search="true" required>

                        @if(isset($products) && $products -> count() > 0)
                        @foreach($products as $product)


                        <option value="{{ $product->id }}">{{ $product->name }}</option>
                        @endforeach
                        @endif
                    </select>
                    @error('name')
                    <small class="'form-text text-danger">{{$message}}</small>
                    @enderror
                </div>


                    <div class="form-group">
                        <label for="formGroupExampleInput2">category</label>
                        <select name="category_id" class=" form-control   selectpicker" multiple="multiple" data-live-search="true" required>
                            @if(isset($allcategories) && $allcategories -> count() > 0)
                            @foreach($allcategories as $allcategory)


                            <option value="{{ $allcategory->id }}">{{ $allcategory->name }}</option>
                            @endforeach
                            @endif
                        </select>

                        @error('category')
                        <small class="'form-text text-danger">{{$message}}</small>
                        @enderror
                    </div>

                            <button type="submit" class="btn btn-primary p-2 m-2">Submit</button>
                        </div>

                    </div>

            </form>
        </div>

        <div class="col-sm">

        </div>
    </div>

</div>



@endsection

resources/views/admin/pages/category/category.blade.php
@extends('admin.layout.app')
@section('content')

@if(Session::has('success'))
<div class="alert alert-success" role="alert">

    <h5>{{Session::get('success')}}</h5>
</div>
@endif
@if(Session::has('deletemessage'))
<div class="alert alert-danger" role="alert">
  <h5> {{Session::get('deletemessage')}}</h5>
</div>
@endif
@if(Session::has('successp'))
<div class="alert alert-success" role="alert">
    <h5>{{Session::get('successp')}}</h5>
</div>
@endif

    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
        <!-- Navbar -->


        <!-- End Navbar -->


        <div class="helen">
            <a href="{{ Route('admin.createcategory') }}" class="btn btn-success p-2  ">create</a>
        </div>


        @if(isset($categories) && $categories -> count() > 0)
        @foreach($categories as $category)
            <h5>{{$category->name}}</h5>
            <div class="helen">

        <a href="{{ route('admin.showproduct',$category->id) }}" class="btn btn-primary p-2">show related product</a>
        <a href="{{ route('admin.editcategory',$category->id) }}" class="btn btn-success p-2">edit category name</a>
        <a href="{{ route('admin.deletecategory',$category->id) }}" class="btn btn-danger p-2">delete category </a>
            </div>
{{--     <p> {{ $category->product->name}}</p>--}}
        @endforeach
        @endif





@endsection

resources/views/admin/pages/category/createcategory.blade.php
@extends('admin.layout.app')
@section('content')







    <div class="container">

        <div class="row x">

            <div class=" col-12">
                <br>
                <br>
                <br>
                <form  action="{{ route('admin.storecategory') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">


                        <div class="form-group">
                            <label for="formGroupExampleInput">name of category</label>
                            <input type="text" name="name"  id="name-of-product" placeholder="name of category">
                            @error('name')
                            <small class="'form-text text-danger">{{$message}}</small>
                            @enderror
                        </div>

                                <br>
                                <div>
                                    <button type="submit" class="btn btn-primary p-2 m-2">Submit</button>
                                </div>

                            </div>

                </form>
            </div>

            <div class="col-sm">

            </div>
        </div>

    </div>



@endsection

resources/views/admin/pages/category/editcategory.blade.php
@extends('admin.layout.app')
@section('content')







<div class="container">

    <div class="row x">

        <div class=" col-12">
            <br>
            <br>
            <br>
            <form  action="{{ route('admin.updatecategory',$category->id) }}" method="POST" enctype="multipart/form-data">
                @csrf


                <div class="form-group">
                    <label for="formGroupExampleInput">name of category</label>
                    <input type="text" name="name"  id="name-of-category" placeholder="name of category">
                    @error('name')
                    <small class="'form-text text-danger">{{$message}}</small>
                    @enderror
                </div>

                        <br>
                        <div>
                            <button type="submit" class="btn btn-primary p-2 m-2">Submit</button>
                        </div>

                    </div>

            </form>
        </div>

        <div class="col-sm">

        </div>
    </div>

</div>



@endsection

resources/views/admin/pages/category/relatedproduct.blade.php
@extends('admin.layout.app')
@section('content')


@if(Session::has('success'))
<div class="alert alert-success" role="alert">
    <h5>{{Session::get('success')}}</h5>
</div>
@endif
@if(Session::has('deletemessage'))
<div class="alert alert-danger" role="alert">
  <h5> {{Session::get('deletemessage')}}</h5>
</div>
@endif
@if(Session::has('deletecatmessage'))
<div class="alert alert-danger" role="alert">
  <h5> {{Session::get('deletemessage')}}</h5>
</div>
@endif
@if(Session::has('successp'))
<div class="alert alert-success" role="alert">
    <h5>{{Session::get('successp')}}</h5>
</div>
@endif

<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">








        <div class="container-fluid py-4">
            @if(isset($categories) && $categories -> count() > 0)


           <div class="helen">

                <a href="{{ Route('admin.makerelatedcat', $categories->id) }}" class="btn btn-primary p-2   ">add relation</a>
            </div>
            {{-- {{ Route('admin.makerelatedcat', $categories->id) }} --}}
            name of Category

           <h4>{{$categories -> name}}</h4>{{ $categories->id }}
@endif
            <table class="table">
                <thead>
                <tr>


                    <th scope="col">product of name</th>
                    <th scope="col">number of product</th>

                    <th scope="col">operation</th>



                </tr>
                </thead>
                <tbody class="m-2">

                    @if(isset($categories) && $categories -> count() > 0)
                        <tr>



                                @foreach ($categories->products as $product )
                                <td scope="col">  <span></span>{{ $product-> name }}..</span>

                                </td>
                            <td scope="col">{{ $product -> productnumber}}</td>


                            <td class=""> <div class="" >


                                    <a href="{{ Route('admin.deleteproductcat', $product->id) }}" class="btn btn-danger p-2   ">delete</a>
{{--                                    --}}


                                    <a href="{{route('admin.deleterelation', ['id'=>"$product->id", 'category_id'=>"$categories->id"])}}" class="btn btn-danger p-2   " > delete relation</a>
                                    {{-- {{ Route('admin.deleterelation', $product->id) }} --}}
                            </div>
                        </td>
                        </tr>
                            @endforeach
                            @endif
                        </tbody>


            </table>

    </main>










@endsection