routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\InventoryController;
use App\Http\Controllers\Admin\OrderController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


//=======authentication=======
Route::get('/dashboard',[HomeController::class, 'dash'])->middleware(['auth', 'verified','CheckAdmin'])->name('admin.dashboard');

Route::get('/redirect',[HomeController::class,'redirect']);

//Route::get('/redirect/',[HomeController::class,'redirect']);

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';






//Route::get('/home', [App\Http\Controllers\Controller::class,'dashboard'])->name('dashboard');
Route::middleware(['CheckAdmin'])->group(function () {
    Route::name('admin.')->group(function () {


        Route::get('/inventory', function () {
            return view('admin.pages.inventory.inventory');
        })->name('inventory');


//createproduct==========================


        Route::get('/product', [ProductController::class, 'index'])->name('product');


        Route::get('/createproduct', [ProductController::class, 'create'])->name('createproduct');
        Route::post('/storeproduct', [ProductController::class, 'store'])->name('storeproduct');
//Route::get('/show1',[ProductController::class, 'index1'])->name('show1');
        Route::get('/related/{id}', [ProductController::class, 'related'])->name('makerelated');
        Route::post('/storerelated', [ProductController::class, 'storeRelated'])->name('storerelated');
        Route::get('show', [ProductController::class, 'show'])->name('showproductdetails');
        Route::get('/editproduct/{id}', [ProductController::class, 'edit'])->name('editproduct');
        Route::post('/updateproduct/{id}', [ProductController::class, 'update'])->name('updateproduct');
        Route::get('/deleteproduct/{id}', [ProductController::class, 'destroy'])->name('deleteproduct');
        Route::get('/showdetailsproduct/{id}', [ProductController::class, 'show'])->name('showdetailsproduct');


        //====================category==========
        Route::get('/createcategory', [CategoryController::class, 'create'])->name('createcategory');
        Route::post('/storecategory', [CategoryController::class, 'store'])->name('storecategory');
        Route::get('/category', [CategoryController::class, 'index'])->name('category');
        Route::get('/showproduct/{category_id}', [CategoryController::class, 'showProduct'])->name('showproduct');
        Route::get('/deleteproductcat/{id}', [CategoryController::class, 'delete'])->name('deleteproductcat');

        Route::get('/editcategory/{id}', [CategoryController::class, 'edit'])->name('editcategory');
        Route::post('/updatecategory/{id}', [CategoryController::class, 'update'])->name('updatecategory');
        Route::get('/deletecategory/{id}', [CategoryController::class, 'destroy'])->name('deletecategory');
        Route::get('/deleterelation/{id}', [CategoryController::class, 'destroyRelation'])->name('deleterelation');
        Route::get('/relatedcat/{id}', [CategoryController::class, 'relatedCat'])->name('makerelatedcat');
        Route::post('/storerelatedcat', [CategoryController::class, 'storeRelated'])->name('storerelatedcat');
        //===========================User====================
        Route::get('/createuser', [UserController::class, 'create'])->name('createuser');
        Route::post('/storeuser', [UserController::class, 'store'])->name('storeuser');
        Route::get('/user', [UserController::class, 'index'])->name('user');

        Route::get('/edituser/{id}', [UserController::class, 'edit'])->name('edituser');
        Route::post('/updateuser/{id}', [UserController::class, 'update'])->name('updateuser');
        Route::get('/deleteuser/{id}', [UserController::class, 'destroy'])->name('deleteuser');
        Route::get('/showuser/{id}', [UserController::class, 'show'])->name('showuser');

//================================Inventory=========================


        Route::get('/creatinv', [InventoryController::class, 'create'])->name('createinv');
        Route::post('/storeinv', [InventoryController::class, 'store'])->name('storeinv');
        Route::get('/inventory', [InventoryController::class, 'index'])->name('inventory');

        Route::get('/editinv/{id}', [InventoryController::class, 'edit'])->name('editinv');
        Route::post('/updateinv/{id}', [InventoryController::class, 'update'])->name('updateinv');


//=================Orders========
        Route::get('/orders', [OrderController::class, 'index'])->name('orders');
        Route::get('/delivered/{created_at}', [OrderController::class, 'delivered'])->name('delivered');
//        Route::get('/deliveredone/{id}', [OrderController::class, 'deliveredOne'])->name('deliveredone');
        Route::get('/showorderdetails/{id}', [OrderController::class, 'showOrderdetails'])->name('showorderdetails');
        Route::get('/showallorders/{name}', [OrderController::class, 'showAllOrders'])->name('showallorders');
    });
});

routes/web.php
<?php

use App\Http\Controllers\Front\CartController;
use App\Http\Controllers\Front\OrderController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index']);



Route::get('/redirect',[HomeController::class,'redirect']);
Route::get('/home', [HomeController::class, 'home'])->name('home');
Route::get('/show/{id}', [HomeController::class, 'show'])->name('showpro');


//=========================Cart====

Route::get('/deletcat/{id}', [CartController::class, 'destroy'])->name('deletcat');
Route::get('/showprowebdetails/{id}',[CartController::class, 'showProWebDetails'])->name('showprowebdetails');
Route::post('/addtocart/{id}',[CartController::class, 'addToCart'])->name('addtocart');
Route::get('/cart', [CartController::class, 'showCart'])->name('cart');


Route::get('/cashorder', [OrderController::class, 'cashOrder'])->name('cashorder');

app/Models/Inventory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    use HasFactory;
    protected $fillable = [
        'qty','type','product_id'
    ];

    public function product(){ //property
        return $this->belongsTo(Product::class);
            }
}

app/Http/Controllers/Admin/InventoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\inventoryRequest;
use App\Models\Category;
use App\Models\Product;
use App\Models\Inventory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class InventoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $inventories = Inventory::orderby('created_at', 'desc')->get();
        return view('admin.pages.inventory.inventory', compact('inventories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $products = Product::get();
        return view ('admin.pages.inventory.createinventory', compact('products') );
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(inventoryRequest $request)
    {
      //  dd($request);
        // $request->validate([
        //     'qty' => ['required|numeric|max:100000'],
        //     'type' => ['required'],

            // ]);
    $id=$request->product_id;
    $type= $request->type;
    $product=Product::find($request->product_id);
//dd($product);
    $quantity= $product->quantity ;
    //;
    if ($type==0){
        $quantity+=$request->qty;
    }



    elseif($type==1){

        $quantity-=$request->qty;


    }

    if($quantity<0){

        return  redirect()->back()->with('message',['you do not have this amount to ship' ]);
    }





    Product::where('id',$id)->update([

        'quantity' =>  $quantity,
    ]);



        $input = $request->all();

//        $request->validate([
//            'product_id' => 'required',
//            'qty' => 'required|numeric|max:100000',
//            'type' => 'required',
//        ]);

       Inventory::create([
        'qty' =>$request->qty,
        'type' =>$request->type,
        'product_id' =>$request->product_id
       ]);
        return redirect('/admin/inventory')->with(['success' => ' تم التعديل على الكمية بنجاح بسجل جديد']);
    }

    /**,
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        return view('admin.pages.inventory.editinventory')
        ->with('inventory',Inventory::where('id',$id)->first());

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(inventoryRequest $request, string $id)
    {
        $oldinventory=Inventory::find($id);
        $product=Product::where('id',$oldinventory->product_id)->first();
//        dd($oldinventory->product_id);
        $quantity=$product->quantity;

        $oldquantity= $oldinventory->qty;
        $oldtype=$oldinventory->type;
        $type= $request->type;
        if ($type==0  ){
            if ($request->qty >=$oldquantity && $oldtype==0){
                $quantity+=$request->qty-$oldquantity;
            }
            elseif ($oldtype==1){
                $quantity+= $request-> qty + $oldquantity;
            }
            elseif ($request-> qty < $oldquantity && $oldtype==0){
                $quantity-=   $oldquantity - $request-> qty;
            }

        }



        elseif($type==1){

            if ( $oldtype==0){
                $quantity-=  $request-> qty + $oldquantity;
            }
//            ifelse ($request->qty < $oldquantity && $oldtype==0){
//            $quantity-= $request-> qty + $oldquantity;
//
//            }
           else if ($request->qty >= $oldquantity && $oldtype==1){
            $quantity-=  $request-> qty - $oldquantity;

                                }
            else{

                $quantity+=  $oldquantity - $request-> qty;
            }

        }

        if($quantity<0){

         return  redirect()->back()->with('message',['you do not have this amount to ship' ]);
       }
        Product::where('id',$oldinventory->product_id)->update([

            'quantity' =>  $quantity,
        ]);

//        $request->validate([
//            'qty' => 'required|numeric|max:100000',
//            'type' => 'required',
//
//        ]);

        Inventory::where('id',$id)->update([
            'qty' => $request->qty,
            'type' => $request->type,
        ]);

        return redirect('/admin/inventory')->with(['success' => 'تم تعديل الفئة بنجاح']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/admin/pages/inventory/createinventory.blade.php
@extends('admin.layout.app')
@section('content')

    @if(Session::has('message'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('message')}}</h5>
        </div>
    @endif
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">





    <div class="container">

        <div class="row x">

            <div class=" col-12">
                <br>
                <br>
                <br>
                <form  action="{{ route('admin.storeinv') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">
                        <label for="formGroupExampleInput2">product </label>
                        <select name="product_id" class=" form-control   selectpicker" value="chose one"  data-live-search="true" required>
                            @if(isset($products) && $products -> count() > 0)
                            @foreach($products as $product)

                                    <option value="{{ $product->id }}"><strong>{{ $product->name }}</strong>        (and you have {{$product->quantity}})</option>

                            @endforeach
                            @endif
                        </select>

                        @error('product_id')
                        <small class="'form-text text-danger">{{$message}}</small>
                        @enderror
                    </div>


                    <div class="form-group">
                        <label for="formGroupExampleInput">type of operation</label>
                        <select name="type"  class=" form-control   selectpicker" multiple="multiple" data-live-search="true">



                            <option value="0">add</option>
                            <option value="1">subtract</option>

                        </select>
                        @error('type')
                        <small class="'form-text text-danger">{{$message}}</small>
                        @enderror



                        <label for="formGroupExampleInput">quantity</label>

                        <input type="text" name="qty"  id="Offer Name" placeholder="quantity">
                        @error('qty')
                        <small class="'form-text text-danger">{{$message}}</small>
                        @enderror

                                <button type="submit" class="btn btn-primary p-2 m-2">Submit</button>
                            </div>

                        </div>

                </form>
            </div>

            <div class="col-sm">

            </div>
        </div>

    </div>





@endsection

resources/views/admin/pages/inventory/editinventory.blade.php
@extends('admin.layout.app')
@section('content')

    @if(Session::has('message'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('message')}}</h5>
        </div>
    @endif
    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">





        <div class="container">

            <div class="row x">

                <div class=" col-12">
                    <br>
                    <br>
                    <br>
                    <form  action="{{ route('admin.updateinv',$inventory->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group">
                            <label for="formGroupExampleInput2">product </label>
                            <select name="product_id" class=" form-control   selectpicker" value="chose one"  data-live-search="true" required>


                                        <option value="{{ $inventory->product->id }}"><strong>{{ $inventory->product->name }}</strong>        (and you have {{$inventory->product->quantity}})</option>



                            </select>

                            @error('name')
                            <small class="'form-text text-danger">{{$message}}</small>
                            @enderror
                        </div>


                        <div class="form-group">
                            <label for="formGroupExampleInput">type of operation</label>
                            <select name="type"  class=" form-control   selectpicker" multiple="multiple" data-live-search="true" >



                                <option value="0">add</option>
                                <option value="1">subtract</option>


                            </select>

                            @error('type')
                            <small class="'form-text text-danger">{{$message}}</small>
                            @enderror

                            <label for="formGroupExampleInput">quantity</label>

                            <input type="text" name="qty"  id="Offer Name" placeholder="quantity" value="{{$inventory->quantity}}">

                            @error('qty')
                            <small class="'form-text text-danger">{{$message}}</small>
                            @enderror

                            <button type="submit" class="btn btn-primary p-2 m-2">Submit</button>
                        </div>

                </div>

                </form>
            </div>

            <div class="col-sm">

            </div>
        </div>

        </div>





@endsection

resources/views/admin/pages/inventory/inventory.blade.php
@extends('admin.layout.app')
@section('content')



    @if(Session::has('success'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('success')}}</h5>
        </div>
    @endif
    @if(Session::has('message'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('message')}}</h5>
        </div>
    @endif

  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <!-- Navbar -->


    <div class="container-fluid py-4">


        <div class="helen">
            <a href="{{ Route('admin.createinv') }}" class="btn btn-success p-2  ">create</a>
        </div>


        <table class="table" id="mytable">
            <thead>
            <tr>

                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Date</th>

                <th scope="col">Type</th>
                <th scope="col">Operation</th>



            </tr>
            </thead>
            <tbody>

                    @foreach($inventories as $inventory)
                    <tr>


                        <th scope="col">{{ $inventory->product->name }}</th>
                        <td scope="col">{{$inventory ->qty}}</td>
                        <td scope="col">{{$inventory ->updated_at}}</td>

                        <td scope="col">@if($inventory->type==0)
                                         <p>add</p>
                                        @else
                                        <p>subtract</p>
                                        @endif
                        </td>

                        <td> <div >


                                <a href="{{ Route('admin.editinv', $inventory->id) }}" class="btn btn-primary p-2  ">edite</a>




                        </div>
                    </td>
                    </tr>
                        @endforeach
                    </tbody>


        </table>

@endsection