routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\InventoryController;
use App\Http\Controllers\Admin\OrderController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


//=======authentication=======
Route::get('/dashboard',[HomeController::class, 'dash'])->middleware(['auth', 'verified','CheckAdmin'])->name('admin.dashboard');

Route::get('/redirect',[HomeController::class,'redirect']);

//Route::get('/redirect/',[HomeController::class,'redirect']);

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';






//Route::get('/home', [App\Http\Controllers\Controller::class,'dashboard'])->name('dashboard');
Route::middleware(['CheckAdmin'])->group(function () {
    Route::name('admin.')->group(function () {


        Route::get('/inventory', function () {
            return view('admin.pages.inventory.inventory');
        })->name('inventory');


//createproduct==========================


        Route::get('/product', [ProductController::class, 'index'])->name('product');


        Route::get('/createproduct', [ProductController::class, 'create'])->name('createproduct');
        Route::post('/storeproduct', [ProductController::class, 'store'])->name('storeproduct');
//Route::get('/show1',[ProductController::class, 'index1'])->name('show1');
        Route::get('/related/{id}', [ProductController::class, 'related'])->name('makerelated');
        Route::post('/storerelated', [ProductController::class, 'storeRelated'])->name('storerelated');
        Route::get('show', [ProductController::class, 'show'])->name('showproductdetails');
        Route::get('/editproduct/{id}', [ProductController::class, 'edit'])->name('editproduct');
        Route::post('/updateproduct/{id}', [ProductController::class, 'update'])->name('updateproduct');
        Route::get('/deleteproduct/{id}', [ProductController::class, 'destroy'])->name('deleteproduct');
        Route::get('/showdetailsproduct/{id}', [ProductController::class, 'show'])->name('showdetailsproduct');


        //====================category==========
        Route::get('/createcategory', [CategoryController::class, 'create'])->name('createcategory');
        Route::post('/storecategory', [CategoryController::class, 'store'])->name('storecategory');
        Route::get('/category', [CategoryController::class, 'index'])->name('category');
        Route::get('/showproduct/{category_id}', [CategoryController::class, 'showProduct'])->name('showproduct');
        Route::get('/deleteproductcat/{id}', [CategoryController::class, 'delete'])->name('deleteproductcat');

        Route::get('/editcategory/{id}', [CategoryController::class, 'edit'])->name('editcategory');
        Route::post('/updatecategory/{id}', [CategoryController::class, 'update'])->name('updatecategory');
        Route::get('/deletecategory/{id}', [CategoryController::class, 'destroy'])->name('deletecategory');
        Route::get('/deleterelation/{id}', [CategoryController::class, 'destroyRelation'])->name('deleterelation');
        Route::get('/relatedcat/{id}', [CategoryController::class, 'relatedCat'])->name('makerelatedcat');
        Route::post('/storerelatedcat', [CategoryController::class, 'storeRelated'])->name('storerelatedcat');
        //===========================User====================
        Route::get('/createuser', [UserController::class, 'create'])->name('createuser');
        Route::post('/storeuser', [UserController::class, 'store'])->name('storeuser');
        Route::get('/user', [UserController::class, 'index'])->name('user');

        Route::get('/edituser/{id}', [UserController::class, 'edit'])->name('edituser');
        Route::post('/updateuser/{id}', [UserController::class, 'update'])->name('updateuser');
        Route::get('/deleteuser/{id}', [UserController::class, 'destroy'])->name('deleteuser');
        Route::get('/showuser/{id}', [UserController::class, 'show'])->name('showuser');

//================================Inventory=========================


        Route::get('/creatinv', [InventoryController::class, 'create'])->name('createinv');
        Route::post('/storeinv', [InventoryController::class, 'store'])->name('storeinv');
        Route::get('/inventory', [InventoryController::class, 'index'])->name('inventory');

        Route::get('/editinv/{id}', [InventoryController::class, 'edit'])->name('editinv');
        Route::post('/updateinv/{id}', [InventoryController::class, 'update'])->name('updateinv');


//=================Orders========
        Route::get('/orders', [OrderController::class, 'index'])->name('orders');
        Route::get('/delivered/{created_at}', [OrderController::class, 'delivered'])->name('delivered');
//        Route::get('/deliveredone/{id}', [OrderController::class, 'deliveredOne'])->name('deliveredone');
        Route::get('/showorderdetails/{id}', [OrderController::class, 'showOrderdetails'])->name('showorderdetails');
        Route::get('/showallorders/{name}', [OrderController::class, 'showAllOrders'])->name('showallorders');
    });
});

routes/web.php
<?php

use App\Http\Controllers\Front\CartController;
use App\Http\Controllers\Front\OrderController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index']);



Route::get('/redirect',[HomeController::class,'redirect']);
Route::get('/home', [HomeController::class, 'home'])->name('home');
Route::get('/show/{id}', [HomeController::class, 'show'])->name('showpro');


//=========================Cart====

Route::get('/deletcat/{id}', [CartController::class, 'destroy'])->name('deletcat');
Route::get('/showprowebdetails/{id}',[CartController::class, 'showProWebDetails'])->name('showprowebdetails');
Route::post('/addtocart/{id}',[CartController::class, 'addToCart'])->name('addtocart');
Route::get('/cart', [CartController::class, 'showCart'])->name('cart');


Route::get('/cashorder', [OrderController::class, 'cashOrder'])->name('cashorder');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;
    protected $fillable = [
         'price', 'quantity',  'product_id', 'user_id', 'payment_status',  'delivery_status'
    ];
    //'name', 'email','photo', 'product',
    public function user(){ //property
        return $this->belongsTo(User::class);
    }
    public function product(){ //property
        return $this->belongsTo(Product::class);
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Traits\ProductTrait;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Product;
use App\Models\Inventory;
use App\Models\Category;
use App\Models\Cart;
use App\Models\Order;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{


    /**
     * Display a listing of the resource.
     */
    public function index()
    {
       // $orders=Order::get()
        $myCollection=Order::orderby('created_at', 'desc')->get();

        $uniqueCollection = $myCollection->unique(['user_id']);




     // $uniqueCollection->all();


   //     dd($uniqueCollection);

//        $allorders=Order::get();
//
//        $orders=Order::where('email',$allorders->email)->where('created_at',$allorders->created_at)->get(first);
        return view('admin.pages.orders.orders', compact('uniqueCollection'));

    }
    public function delivered(Request $request){

        $order=Order::find($request->created_at);
        $prices=Order::where('created_at',$request->created_at)->update([
            'delivery_status'=> 'Delivered',
        ]);

//        $order->delivery_status="delivered";
//        $order->save;
        return redirect()->back();
    }



    public function showOrderdetails( Request $request){

        $id="$request->user_id";
        $created_at="$request->created_at";
        $myCollection=Order::orderby('created_at', 'desc')->where('user_id',$request->id)->get();
     //   Order::where('created_at',$request->created_at)->get();
//        $packages=$myCollection->where(['created_at']);

        $orders = $myCollection->unique(['created_at']);
//        $price=0;
//            foreach($packages as $package){
//                $price += $package->price;
//
//            }

    // $orders=Order::orderby('created_at', 'desc')->where('user_id',$id)->get();


    // dd($orders);
     return view('admin.pages.orders.orderspackge',compact(['orders']));
    }


    public function showAllOrders($id){
        $orders=Order::orderby('created_at', 'desc')->where('created_at',$id)->get();
        return view('admin.pages.orders.allorderspackge',compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}



//
//
//
//public function deliveredOne($id){
//    $order=Order::find($id);
//    $prices=Order::where('id',$id)->update([
//        'delivery_status'=> 'Delivered',
//    ]);
//
////        $order->delivery_status="delivered";
////        $order->save;
//    return redirect()->back();
//}

app/Http/Controllers/Front/OrderController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Traits\ProductTrait;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Product;
use App\Models\Inventory;
use App\Models\Category;
use App\Models\Cart;
use App\Models\Order;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     */

    public function cashOrder(){

        $user=Auth::user();
        $userid=$user->id;
        $datac=Cart::where('user_id', $userid)->get();
   //     dd($data);

        foreach ($datac as $data)
        {
            $order=Order::create([
//                'name'=>$data->name,
//                'email'=>$data->email,
                'user_id'=>$data->user_id,
//                'product'=>$data->product,
                'price'=>$data->price * $data->quantity,
                'photo'=>$data->photo,
                'product_id'=>$data->product_id,
                'quantity'=>$data->quantity,
                'payment_status' =>'cash on delivery',
                'delivery_status' => 'processing',
            ]);

            $product_iid=$data->product_id;

            $product=Product::find($product_iid);
//            dd($product);
            $qty= $product->quantity;

            $qty -= $data->quantity;
            Inventory::create([
                'qty' =>$data->quantity,
                'type' => 1,
                'product_id' =>$product_iid
            ]);



            Product::where('id', $product_iid)->update([

                'quantity' => $qty ,
            ]);








            $cart_id=$data->id;
            $cart=Cart::find($cart_id);
            $cart->delete();

//            Inventory::where('name',$name);

        }
        return redirect('cart')->with('message', 'We have received your order. we will connect you soon...');

    }



    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/admin/pages/orders/allorderspackge.blade.php
@extends('admin.layout.app')
@section('content')


<div>
    <h3 class="text-center"> All Orders</h3>
</div>


    <table class="table" id="mytable">
        <thead>
        <tr>
            <th scope="col">user name</th>
            <th scope="col">email</th>
            <th scope="col">phone</th>
            <th scope="col">address</th>
{{--            <th scope="col">Product</th>--}}
{{--            <th scope="col">Quantity</th>--}}
            <th scope="col">Date</th>
            <th scope="col">price</th>
            <th scope="col">delivery status</th>






        </tr>
        </thead>
        <tbody>

        @foreach($orders as $order)
            <tr>


                <th scope="col">{{ $order->user->name }}</th>
                <td scope="col">{{$order ->user->email}}</td>
                <td scope="col">{{$order ->user->phone}}</td>
                <td scope="col">{{$order ->user->address}}</td>
{{--                <td> {{$order->product->name}} </td>--}}
{{--                <td scope="col">{{$order ->quantity}}</td>--}}
                <td scope="col">{{$order ->updated_at}}</td>
                <td scope="col">{{$order ->price}} $</td>
                <td scope="col">
                    @if($order->delivery_status=='processing')
                        {{$order->delivery_status}}
                        <a href="" class="btn btn-primary m-1">Delivered</a>
{{--                        {{route('admin.deliveredone',$order->id)}}                       onclick="return confirm('Are you sure this product is delivered')" --}}
                    @else
                        <p>Delivered</p>
                    @endif

                </td>





            </tr>
        @endforeach
        </tbody>


    </table>
@endsection

resources/views/admin/pages/orders/orders.blade.php
@extends('admin.layout.app')
@section('content')


<div>
    <h3 class="text-center"> All Orders</h3>
</div>


    <table class="table" id="mytable">
        <thead>
        <tr>
            <th scope="col">user name</th>
            <th scope="col">email</th>
            <th scope="col">phone</th>
            <th scope="col">address</th>

{{--            <th scope="col">delivery status</th>--}}
            <th scope="col">operation</th>




        </tr>
        </thead>
        <tbody>

        @foreach($uniqueCollection as $order)
            <tr>


                <th scope="col">{{ $order->user->name }}</th>
                <td scope="col">{{$order ->user->email}}</td>
                <td scope="col">{{$order ->user->phone}}</td>
                <td scope="col">{{$order ->user->address}}</td>


{{--                <td scope="col">--}}
{{--                    @if($order->delivery_status=='processing')--}}
{{--                        {{$order->delivery_status}}--}}
{{--                        <a href="{{route('admin.delivered',$order->created_at)}}" onclick="return confirm('Are you sure this product is delivered')" class="btn btn-primary m-1">Delivered</a>--}}
{{--                    @else--}}
{{--                        <p>Delivered</p>--}}
{{--                    @endif--}}

{{--                </td>--}}




                <td scope="col"><a href="{{route('admin.showorderdetails', ['id'=>"$order->user_id"])}}" class="btn btn-success">show order</a></td>



            </tr>
        @endforeach
        </tbody>


    </table>
@endsection

resources/views/admin/pages/orders/orderspackge.blade.php
@extends('admin.layout.app')
@section('content')


<div>
    <h3 class="text-center"> All Orders</h3>
</div>


    <table class="table" id="mytable">
        <thead>
        <tr>
            <th scope="col">user name</th>
            <th scope="col">email</th>
            <th scope="col">phone</th>
            <th scope="col">address</th>
{{--            <th scope="col">Product</th>--}}
{{--            <th scope="col">Quantity</th>--}}
{{--            <th scope="col">Date</th>--}}
{{--            <th scope="col">price</th>--}}
            <th scope="col">delivery status</th>
            <th scope="col">details</th>





        </tr>
        </thead>
        <tbody>

        @foreach($orders as $order)
            <tr>


                <th scope="col">{{ $order->user->name }}</th>
                <td scope="col">{{$order ->user->email}}</td>
                <td scope="col">{{$order ->user->phone}}</td>
                <td scope="col">{{$order ->user->address}}</td>
{{--                <td> {{$order->product->name}} </td>--}}
{{--                <td scope="col">{{$order ->quantity}}</td>--}}
{{--                <td scope="col">{{$order ->updated_at}}</td>--}}
{{--                <td scope="col">{{$price}} $</td>--}}
                <td scope="col">
                    @if($order->delivery_status=='processing')
                        {{$order->delivery_status}}
                        <a href="{{route('admin.delivered', ['created_at'=>"$order->created_at"])}}" onclick="return confirm('Are you sure this product is delivered')" class="btn btn-primary m-1">Delivered</a>
                    @else
                        <p>Delivered</p>
                    @endif

                </td>

                <td scope="col"><a href="{{route('admin.showallorders', $order->created_at)}}" class="btn btn-success">show all order</a></td>



            </tr>
        @endforeach
        </tbody>


    </table>
@endsection