routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\InventoryController;
use App\Http\Controllers\Admin\OrderController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


//=======authentication=======
Route::get('/dashboard',[HomeController::class, 'dash'])->middleware(['auth', 'verified','CheckAdmin'])->name('admin.dashboard');

Route::get('/redirect',[HomeController::class,'redirect']);

//Route::get('/redirect/',[HomeController::class,'redirect']);

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';






//Route::get('/home', [App\Http\Controllers\Controller::class,'dashboard'])->name('dashboard');
Route::middleware(['CheckAdmin'])->group(function () {
    Route::name('admin.')->group(function () {


        Route::get('/inventory', function () {
            return view('admin.pages.inventory.inventory');
        })->name('inventory');


//createproduct==========================


        Route::get('/product', [ProductController::class, 'index'])->name('product');


        Route::get('/createproduct', [ProductController::class, 'create'])->name('createproduct');
        Route::post('/storeproduct', [ProductController::class, 'store'])->name('storeproduct');
//Route::get('/show1',[ProductController::class, 'index1'])->name('show1');
        Route::get('/related/{id}', [ProductController::class, 'related'])->name('makerelated');
        Route::post('/storerelated', [ProductController::class, 'storeRelated'])->name('storerelated');
        Route::get('show', [ProductController::class, 'show'])->name('showproductdetails');
        Route::get('/editproduct/{id}', [ProductController::class, 'edit'])->name('editproduct');
        Route::post('/updateproduct/{id}', [ProductController::class, 'update'])->name('updateproduct');
        Route::get('/deleteproduct/{id}', [ProductController::class, 'destroy'])->name('deleteproduct');
        Route::get('/showdetailsproduct/{id}', [ProductController::class, 'show'])->name('showdetailsproduct');


        //====================category==========
        Route::get('/createcategory', [CategoryController::class, 'create'])->name('createcategory');
        Route::post('/storecategory', [CategoryController::class, 'store'])->name('storecategory');
        Route::get('/category', [CategoryController::class, 'index'])->name('category');
        Route::get('/showproduct/{category_id}', [CategoryController::class, 'showProduct'])->name('showproduct');
        Route::get('/deleteproductcat/{id}', [CategoryController::class, 'delete'])->name('deleteproductcat');

        Route::get('/editcategory/{id}', [CategoryController::class, 'edit'])->name('editcategory');
        Route::post('/updatecategory/{id}', [CategoryController::class, 'update'])->name('updatecategory');
        Route::get('/deletecategory/{id}', [CategoryController::class, 'destroy'])->name('deletecategory');
        Route::get('/deleterelation/{id}', [CategoryController::class, 'destroyRelation'])->name('deleterelation');
        Route::get('/relatedcat/{id}', [CategoryController::class, 'relatedCat'])->name('makerelatedcat');
        Route::post('/storerelatedcat', [CategoryController::class, 'storeRelated'])->name('storerelatedcat');
        //===========================User====================
        Route::get('/createuser', [UserController::class, 'create'])->name('createuser');
        Route::post('/storeuser', [UserController::class, 'store'])->name('storeuser');
        Route::get('/user', [UserController::class, 'index'])->name('user');

        Route::get('/edituser/{id}', [UserController::class, 'edit'])->name('edituser');
        Route::post('/updateuser/{id}', [UserController::class, 'update'])->name('updateuser');
        Route::get('/deleteuser/{id}', [UserController::class, 'destroy'])->name('deleteuser');
        Route::get('/showuser/{id}', [UserController::class, 'show'])->name('showuser');

//================================Inventory=========================


        Route::get('/creatinv', [InventoryController::class, 'create'])->name('createinv');
        Route::post('/storeinv', [InventoryController::class, 'store'])->name('storeinv');
        Route::get('/inventory', [InventoryController::class, 'index'])->name('inventory');

        Route::get('/editinv/{id}', [InventoryController::class, 'edit'])->name('editinv');
        Route::post('/updateinv/{id}', [InventoryController::class, 'update'])->name('updateinv');


//=================Orders========
        Route::get('/orders', [OrderController::class, 'index'])->name('orders');
        Route::get('/delivered/{created_at}', [OrderController::class, 'delivered'])->name('delivered');
//        Route::get('/deliveredone/{id}', [OrderController::class, 'deliveredOne'])->name('deliveredone');
        Route::get('/showorderdetails/{id}', [OrderController::class, 'showOrderdetails'])->name('showorderdetails');
        Route::get('/showallorders/{name}', [OrderController::class, 'showAllOrders'])->name('showallorders');
    });
});

routes/web.php
<?php

use App\Http\Controllers\Front\CartController;
use App\Http\Controllers\Front\OrderController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index']);



Route::get('/redirect',[HomeController::class,'redirect']);
Route::get('/home', [HomeController::class, 'home'])->name('home');
Route::get('/show/{id}', [HomeController::class, 'show'])->name('showpro');


//=========================Cart====

Route::get('/deletcat/{id}', [CartController::class, 'destroy'])->name('deletcat');
Route::get('/showprowebdetails/{id}',[CartController::class, 'showProWebDetails'])->name('showprowebdetails');
Route::post('/addtocart/{id}',[CartController::class, 'addToCart'])->name('addtocart');
Route::get('/cart', [CartController::class, 'showCart'])->name('cart');


Route::get('/cashorder', [OrderController::class, 'cashOrder'])->name('cashorder');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'user_type',
        'name',
        'email',
        'phone',
        'address',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function cart(){
        return $this->hasMany(Cart::class);

    }
    public function order(){
        return $this->hasMany(Order::class);


    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\userRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules;
use App\Models\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::get();
        return view('admin.pages.users.mange-user', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        Return view('admin.pages.users.createuser');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(userRequest $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:'.User::class],
            'password' => ['required', 'confirmed', Rules\Password::defaults()],
        ]);

//        $user = User::create([
//            'name' => $request->name,
//            'email' => $request->email,
//            'phone'=> $request->phone,
//            'password' => Hash::make($request->password),
//        ]);
        return redirect('/admin/user')->with(['success' => 'تم إضافة المستخدم بنجاح']);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $user = User::find($id);
        return view ('admin.pages.users.user-details', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        return view('admin.pages.users.edituser')
        ->with('user',User::where('id',$id)->first());
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        User::where('id',$id)
        ->update([  'name' => $request->name,
        'email' => $request->email,
        'password' => Hash::make($request->password),]);
        return redirect('/admin/user')->with(['success' => 'تم تعديل بيانات المستخدم بنجاح']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        User::where('id', $id)->delete();
        return redirect('/admin/user')
        ->with('deletemessage', 'تم حذف المستخدم بنجاح');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/admin/pages/users/createuser.blade.php
@extends('admin.layout.app')
@section('content')







    <div class="container">

        <div class="row x">

            <div class=" col-12">
                <br>
                <br>
                <br>
                <form  action="{{ route('admin.storeuser') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">


                        <div>
                            <x-input-label for="name" :value="__('Name')" />
                            <x-text-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name')" required autofocus autocomplete="name" />
                            <x-input-error :messages="$errors->get('name')" class="mt-2" />
                        </div>
                        <div>
                            <x-input-label for="phone" :value="__('PHONE')" />
                            <x-text-input id="phone" class="block mt-1 w-full" type="text" name="phone" :value="old('phone')" required autofocus autocomplete="phone" />
                            <x-input-error :messages="$errors->get('phone')" class="mt-2" />
                        </div>
                        <div>
                            <x-input-label for="address" :value="__('address')" />
                            <x-text-input id="address" class="block mt-1 w-full" type="text" name="phone" :value="old('address')" required autofocus autocomplete="address" />
                            <x-input-error :messages="$errors->get('address')" class="mt-2" />
                        </div>

                        <!-- Email Address -->
                        <div class="mt-4">
                            <x-input-label for="email" :value="__('Email')" />
                            <x-text-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email')" required autocomplete="username" />
                            <x-input-error :messages="$errors->get('email')" class="mt-2" />
                        </div>

                                        <!-- Password -->
                        <div class="mt-4">
                            <x-input-label for="password" :value="__('Password')" />

                            <x-text-input id="password" class="block mt-1 w-full"
                                            type="password"
                                            name="password"
                                            required autocomplete="new-password" />

                            <x-input-error :messages="$errors->get('password')" class="mt-2" />
                        </div>

                        <!-- Confirm Password -->
                        <div class="mt-4">
                            <x-input-label for="password_confirmation" :value="__('Confirm Password')" />

                            <x-text-input id="password_confirmation" class="block mt-1 w-full"
                                            type="password"
                                            name="password_confirmation" required autocomplete="new-password" />

                            <x-input-error :messages="$errors->get('password_confirmation')" class="mt-2" />
                        </div>
                                                <br>
                                                <div>
                                                    <button type="submit" class="btn btn-primary p-2 m-2">Submit</button>
                                                </div>

                                            </div>

                                </form>
                            </div>

                            <div class="col-sm">

                            </div>
                        </div>

                    </div>



@endsection

resources/views/admin/pages/users/edituser.blade.php
@extends('admin.layout.app')
@section('content')







<div class="container">

    <div class="row x">

        <div class=" col-12">
            <br>
            <br>
            <br>
            <form  action="{{ route('admin.updateuser',$user->id) }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="form-group">


                    <div class="form-group">
                        <label for="formGroupExampleInput">name of user</label>

                        <input type="text" name="name"  id="name-of-user" placeholder="" value="{{ $user->name }}">
                        @error('name')
                        <small class="'form-text text-danger">{{$message}}</small>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="formGroupExampleInput">Email</label>

                        <input type="text" name="email"  id="email" placeholder="" value="{{ $user->email }}">
                        @error('name')
                        <small class="'form-text text-danger">{{$message}}</small>
                        @enderror
                    </div>

                        <label for="formGroupExampleInput">phone</label>
                    <div>
                        <input type="number" name="phone"  id="name-of-user" placeholder="" value="{{ $user->phone }}">

                    </div>

                        <label for="formGroupExampleInput">address</label>
                    <div>
                        <input type="text" name="address"  id="name-of-user" placeholder="" value="{{ $user->address }}">
                    </div>

                    <!-- Email Address -->


                                    <!-- Password -->
                                    <label for="formGroupExampleInput">password</label>

                                    <input type="password" placeholder="Password" id="password" required>
                                    <label for="formGroupExampleInput">confirm password</label>

                                    <input type="password" placeholder="Confirm Password" id="confirm_password" required>
                                    <br>
                                    <div>
                                        <button type="submit" class="btn btn-primary p-2 m-2">Submit</button>
                                    </div>

                            </form>
                        </div>

                        <div class="col-sm">

                        </div>
                    </div>

                </div>

@endsection

resources/views/admin/pages/users/mange-user.blade.php
@extends('admin.layout.app')
@section('content')


@if(Session::has('success'))
<div class="alert alert-success" role="alert">

        <span aria-hidden="true">&times;</span>
      </button>
    <h5>{{Session::get('success')}}</h5>
</div>
@endif
@if(Session::has('deletemessage'))
<div class="alert alert-danger" role="alert">

  <h5> {{Session::get('deletemessage')}}</h5>
</div>
@endif
@if(Session::has('successp'))
<div class="alert alert-success" role="alert">

        <span aria-hidden="true">&times;</span>

    <h5>{{Session::get('successp')}}</h5>
</div>
@endif

<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">








        <div class="container-fluid py-4">


            <div class="helen">
                <a href="{{ Route('admin.createuser') }}" class="btn btn-success p-2  ">create</a>
            </div>


            <table class="table" id="mytable">
                <thead>
                <tr>

                    <th scope="col">user name</th>
                    <th scope="col">email</th>
                    <th scope="col">phone</th>
                    <th scope="col">address</th>
                    <th scope="col">operation</th>



                </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                        @if($user-> user_type == 0)

                        <tr>
                            <td scope="col">
                               {{ $user -> name }}
                                </td>

                            <td scope="col">{{$user -> email}}</td>
                            <td scope="col">{{$user -> phone}}</td>
                            <td scope="col">{{$user -> address}}</td>
                            <td> <div >


                                    <a href="{{ Route('admin.edituser', $user->id) }}" class="btn btn-primary p-2  ">edite</a>

                                    <a href="{{ Route('admin.deleteuser', $user->id) }}" class="btn btn-danger p-2  ">delete</a>

                                    <a href="{{ Route('admin.showuser', $user->id) }}" class="btn btn-warning p-2  ">show details</a>
                            </div>
                        </td>
                        </tr>
                        @endif
                            @endforeach

                        </tbody>


            </table>

    </main>










@endsection

resources/views/admin/pages/users/user-details.blade.php
@extends('admin.layout.app')
@section('content')




<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">

 <p>
    {{ $user->id }}
 </p>
 <h2>
    {{ $user->name }}
 </h2>
<p>
    {{ $user->email}}
</p>
    <p>
        {{$user->phone}}

    </p>
    <p>
        {{$user->address}}
    </p>
<p> <strong> i will edit this page later</strong></p>
    </main>










@endsection